ARG base_image=ghcr.io/atgenomix/runtime/base:1.5_20.04
ARG GITHUB_TOKEN
FROM --platform=$BUILDPLATFORM sbtscala/scala-sbt:eclipse-temurin-17.0.14_7_1.10.10_2.12.20 AS build
ARG base_image
ARG GITHUB_TOKEN

ENV GITHUB_TOKEN=${GITHUB_TOKEN}

WORKDIR /build/
COPY build.sbt /build/
COPY project /build/project/

RUN sbt update

COPY src /build/src
RUN sbt assembly

FROM ${base_image}
ARG base_image
ARG version=1.1.0_sl

# metadata
LABEL \
    org.opencontainers.image.authors="Johan Nystrom-Persson <johan@jnpsolutions.io>" \
    org.opencontainers.image.description="Slacken ${version}" \
    org.opencontainers.image.base.name="${base_image}"
LABEL maintainer="JNP Solutions <info@jnpsolutions.io>"


#This jar file is generated by sbt assembly
COPY --from=build /build/target/scala-2.12/Slacken-assembly-${version}.jar /home/spark-current/jars/


