ARG base_image=ghcr.io/atgenomix/runtime/base:1.5_20.04

FROM ${base_image}
ARG base_image

ARG version=1.1.0_sl

# metadata
LABEL \
    org.opencontainers.image.authors="Johan Nystrom-Persson <johan@jnpsolutions.io>" \
    org.opencontainers.image.description="Slacken ${version}" \
    org.opencontainers.image.base.name="${base_image}"
LABEL maintainer="JNP Solutions <info@jnpsolutions.io>"


#This jar file is generated by sbt assembly
COPY target/scala-2.12/Slacken-assembly-${version}.jar /home/spark-current/jars/


