#!/bin/bash

#Copy AWS EMR output from S3 to local filesystem
#(generated by slacken_pipeline.sh)

#e.g. strain
FAMILY=$1
shift
LNAME=$1
shift
CS="0.00 0.05 0.10 0.15"

ROOT=s3://jnp-bio-us/scratch/classified/cami2

aws s3 sync --exclude "*" --include "*kreport.txt" --include "*metrics.tsv" $ROOT/$FAMILY/$LNAME $FAMILY/$LNAME


for f in $CS
do
aws s3 sync --exclude "*" --include "*kreport.txt" --include "*metrics.tsv" $ROOT/$FAMILY/${LNAME}_c${f}_classified $FAMILY/${LNAME}_c${f}_classified
done


