name: Docker image build

on:
  push:
    branches: [ "seqslab" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag slacken_seqslab:$(date +%s)

